DROP DATABASE IF EXISTS embercat;
DROP USER IF EXISTS embercat;

CREATE USER embercat WITH PASSWORD 'K3H27ppDcNOe';
CREATE DATABASE embercat WITH OWNER embercat;
GRANT ALL PRIVILEGES ON DATABASE embercat TO embercat;
